### ISSUE TITLE
problemi con il pront una volta fatto npm i @angular/cli

### ISSUE THREAD

**Issue by francescolillo24** [ValeriaCom/catalogoProdotti#3]
una volta fatto il comando da pront npm i @angular/cli da questo errore 
![errore npm ](https://user-images.githubusercontent.com/78487863/107983247-c76d4680-6fc5-11eb-9050-bc277262630e.PNG)

**Comment by luca-lezzerini** [comment]
Provate a cancellare la cartella node_modules e a rifare npm i @angular/cli

**Comment by marcobonaccorso** [comment]
> Provate a cancellare la cartella node_modules ea rifare npm i @ angular / cli

Provato (ho conservato una copia del progetto completo) e non va ugualmente.
